version: "3.8"

services:
  app:
    image: fonon-landing-server:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${APP_PORT:-9090}:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}

      # ✅ Map .env variables to Spring Boot vars
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DIALECT: ${JPA_DIALECT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO}

      R2_BUCKET: ${R2_BUCKET}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_PRESIGN_EXPIRY_SECONDS: ${R2_PRESIGN_EXPIRY_SECONDS}

      FILE_STORAGE_BASE_PATH: ${FILE_STORAGE_BASE_PATH}
      FILE_STORAGE_PUBLIC_PATH: ${FILE_STORAGE_PUBLIC_PATH}

    restart: unless-stopped
    volumes:
      - app-storage:/app/storage

volumes:
  app-storage:
