version: "3.8"

services:
  app:
    image: fonon-landing-server:latest
    build:
      context: .
    ports:
      - "${APP_PORT:-9090}:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}

      # ✅ Proper Spring Boot datasource config
      SPRING_DATASOURCE_URL: jdbc:postgresql://185.217.131.110:5432/fonon_landing
      SPRING_DATASOURCE_USERNAME: sardoba_user
      SPRING_DATASOURCE_PASSWORD: sardoba_super_secret_password
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      # Optional tuning (recommended)
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # Other environment variables (Cloudflare etc.)
      R2_BUCKET: ${R2_BUCKET:-my-bucket}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID:-00000000000000000000000000000000}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID:-changeme}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY:-changeme}
      R2_PRESIGN_EXPIRY_SECONDS: ${R2_PRESIGN_EXPIRY_SECONDS:-300}

      FILE_STORAGE_BASE_PATH: ${FILE_STORAGE_BASE_PATH:-/app/storage}
      FILE_STORAGE_PUBLIC_PATH: ${FILE_STORAGE_PUBLIC_PATH:-/storage}

    restart: unless-stopped
    volumes:
      - app-storage:/app/storage

volumes:
  app-storage:
