version: "3.8"

services:
  app:
    build:
      context: .
    image: fonon-landing-server:latest
    env_file:
      - .env
    ports:
      - "${APP_PORT:-9090}:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
    volumes:
      - app-storage:/app/storage

volumes:
  app-storage:
