server:
  port: ${PORT:9090}

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
  main:
    banner-mode: console
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fonon_landing}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs

app:
  storage:
    provider: r2
    bucket: ${R2_BUCKET:my-bucket}
    accountId: ${R2_ACCOUNT_ID:00000000000000000000000000000000}
    accessKey: ${R2_ACCESS_KEY_ID:changeme}
    secretKey: ${R2_SECRET_ACCESS_KEY:changeme}
    endpoint: https://${R2_ACCOUNT_ID:00000000000000000000000000000000}.r2.cloudflarestorage.com
    region: us-east-1
    presignExpirySeconds: ${R2_PRESIGN_EXPIRY_SECONDS:300}
  file-storage:
    base-path: ${FILE_STORAGE_BASE_PATH:src/main/resources/static/storage}
    public-path: ${FILE_STORAGE_PUBLIC_PATH:/storage}
